name: dart_example
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: long1eu <lung.razvan@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  path: ^1.6.0
  sqlite_ffi:
    path: ../../
    
dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
